# Generated by Django 5.2 on 2025-05-17 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='Date_of_Accident',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='Date_of_Admission',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
