# Generated by Django 5.2 on 2025-05-17 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_hospital_profile_hospital'),
        ('core', '0002_alter_incident_date_of_accident_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents_at_hospital', to='accounts.hospital'),
        ),
    ]
